import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {SLOTS,BASE_GRAMS,FINISHES,FINISH_PARTS} from './attachments.js';

// "low-poly AK-74M Zenitco" by D_U, CC BY 4.0. The loose cartridge, case and spare
// magazine lying beside the rifle in the source file were removed (see README).
const MODEL_URL='./model/ak-74m-zenitco.glb';
const SOURCE_URL='https://sketchfab.com/3d-models/low-poly-ak-74m-zenitco-35ad8e37a513453cbbbd04064fa5fb79';
const AUTHOR_URL='https://sketchfab.com/DU1701';
// The model is rescaled to the AK-74M's published overall length (stock extended).
const OVERALL_LENGTH=.943;
// Source node names grouped into selectable parts. Ids that match a socket are swappable.
const PARTS=[
 {id:'receiver',label:'Receiver & bolt group',detail:'AK-74M receiver, dust cover, bolt carrier, recoil spring, trigger, selector and magazine release.',nodes:['ak74m receiver_8','ak74m dust cover_11','ak74m bolt carrier_10','ak74m recoil spring.001_21','ak74m trigga_0','ak74m selector_1','ak74m mag release_2']},
 {id:'rail',label:'B-13 rail mount',detail:'Zenitco B-13 side-mount bracket with a top rail. It carries the optic.',nodes:['b13 bracket_14']},
 {id:'optic',label:'Red dot sight',detail:'Compact red dot on the B-13 rail. It becomes a swappable optic in step 2.',nodes:['vzor1 red dot_20']},
 {id:'handguard',label:'B-10 / B-19 handguard',detail:'Zenitco railed handguard with a lower rail that holds the foregrip.',nodes:['b10+b19 handguard_15']},
 {id:'barrel',label:'Barrel & gas block',detail:'415 mm barrel with front sight and gas block.',nodes:['ak74m barrel_9']},
 {id:'muzzle',label:'DTK-1 muzzle brake',detail:'Zenitco DTK-1 muzzle brake on the threaded muzzle. It becomes swappable in step 2.',nodes:['dtk1 compensator_12']},
 {id:'foregrip',label:'RK-1 foregrip',detail:'Zenitco RK-1 vertical foregrip on the lower handguard rail.',nodes:['rk1 front grip_16']},
 {id:'magazine',label:'Magazine',detail:'30-round 5.45×39 polymer magazine.',nodes:['ak74 30rnd mag (polymer)_6']},
 {id:'grip',label:'RK-9 pistol grip',detail:'Zenitco RK-9 pistol grip.',nodes:['rk9 pistol grip_13']},
 {id:'stock',label:'PT-1 stock',detail:'Zenitco PT-1 stock: base, butt pad and adjustable cheek rest.',nodes:['pt1 stock base_17','pt1 stock butt_18','pt1 cheek_19']}
];
// Mount points in the source file's coordinates (muzzle along +x): position and the direction an attachment extends.
const SOCKETS=[
 ['muzzle','Muzzle',[4.95,.18,0],[1,0,0]],
 ['optic','Optic rail',[.08,.69,0],[0,1,0]],
 ['foregrip','Under rail',[2.5,-.03,0],[0,-1,0]],
 ['magazine','Mag well',[.7,-.2,0],[0,-1,0]],
 ['grip','Grip',[-.8,-.15,0],[0,-1,0]],
 ['stock','Stock',[-1.2,0,0],[-1,0,0]]
];
const accent=0xef8f39;
// Studio is generated by model-source/generate-studio-hdr.py; outdoor and sunset are Poly Haven
// "Quarry 01" and "Venice Sunset" (CC0).
const ENVIRONMENTS={studio:'./lighting/studio.hdr',outdoor:'./lighting/quarry_01_1k.hdr',sunset:'./lighting/venice_sunset_1k.hdr'};

const stage=document.querySelector('#stage'),status=document.querySelector('#status'),detail=document.querySelector('#detail');
const scene=new T.Scene();
let renderer,camera,controls,model,parts=[],sockets=[],selected=null,hovered=null,tweens=[],spinning=false,cameraMove=null,buildBox=new T.Box3();
const build={},slots={},finish={};

// Sources differ in orientation; lay the longest axis along x, then center on the origin.
function normalize(root){
 root.updateMatrixWorld(true);
 let size=new T.Box3().setFromObject(root).getSize(new T.Vector3());
 if(size.z>size.x&&size.z>=size.y)root.rotation.y=Math.PI/2;
 else if(size.y>size.x&&size.y>size.z)root.rotation.z=Math.PI/2;
 root.updateMatrixWorld(true);
 const bounds=new T.Box3().setFromObject(root);size=bounds.getSize(new T.Vector3());
 // The muzzle is the slimmer end: compare vertical extent in the first and last 12% of length.
 const ends=[[Infinity,-Infinity],[Infinity,-Infinity]],v=new T.Vector3();
 root.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld);const t=(v.x-bounds.min.x)/size.x,e=t<.12?ends[0]:t>.88?ends[1]:null;if(e){e[0]=Math.min(e[0],v.y);e[1]=Math.max(e[1],v.y);}}});
 if(ends[0][1]-ends[0][0]<ends[1][1]-ends[1][0])root.rotateY(Math.PI);
 root.updateMatrixWorld(true);
 root.scale.multiplyScalar(OVERALL_LENGTH/size.x);
 root.updateMatrixWorld(true);
 const center=new T.Box3().setFromObject(root).getCenter(new T.Vector3());
 const holder=new T.Group();holder.add(root);root.position.sub(center);return holder;
}

async function loadModel(){
 const root=(await new GLTFLoader().loadAsync(MODEL_URL)).scene;
 // GLTFLoader sanitizes node names (spaces to _, dots dropped), so PARTS keeps the source spelling.
 root.traverse(o=>{if(o.isMesh)o.castShadow=o.receiveShadow=true;});
 const parts=PARTS.map(p=>{const objects=[];for(const name of p.nodes)root.getObjectByName(T.PropertyBinding.sanitizeNodeName(name))?.traverse(o=>{if(o.isMesh)objects.push(o);});return {...p,objects};}).filter(p=>p.objects.length);
 const sockets=SOCKETS.map(([id,label,p,d])=>{const o=new T.Object3D();o.name='socket:'+id;o.position.set(...p);o.userData={id,label,direction:new T.Vector3(...d)};root.add(o);return o;});
 return {root,parts,sockets};
}

// Selected parts glow orange; the part under the pointer gets a faint lift.
function paint(){
 const chosen=new Set(parts.find(p=>p.id===selected)?.objects||[]),hover=new Set(parts.find(p=>p.id===hovered)?.objects||[]);
 model.traverse(o=>{if(!o.isMesh||!o.material.emissive)return;const on=chosen.has(o)||hover.has(o);o.material.emissive.setHex(chosen.has(o)?accent:on?0xffffff:0);o.material.emissiveIntensity=chosen.has(o)?.35:on?.06:0;});
}
function select(id){
 selected=selected===id?null:id;
 const part=parts.find(p=>p.id===selected);
 paint();
 for(const p of parts)p.entry.setAttribute('aria-pressed',String(p.id===selected));
 detail.textContent=part?part.detail:'Select a part on the model or in this list to highlight it.';
}

try{
 renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;stage.prepend(renderer.domElement);
 camera=new T.PerspectiveCamera(35,1,.01,20);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.15;controls.maxDistance=3.5;controls.enablePan=true;

 // Image-based lighting from an HDR environment. The directional key only casts the shadow;
 // it is aimed at the HDR's brightest texel and turns with the environment.
 const key=new T.DirectionalLight(0xffffff,1.6);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-.7,right:.7,top:.7,bottom:-.7,near:.5,far:5});key.shadow.normalBias=.01;key.shadow.radius=4;scene.add(key);
 const hdrLoader=new RGBELoader().setDataType(T.FloatType),environments={};
 let envName='studio',lightAngle=0;
 function brightestDirection(texture){
  const {data,width,height}=texture.image;let best=-1,at=0;
  for(let i=0;i<width*height;i++){const l=data[i*4]*.2126+data[i*4+1]*.7152+data[i*4+2]*.0722;if(l>best){best=l;at=i;}}
  // Row 0 is the top of the equirect; azimuth follows three.js equirect UVs, atan2(z,x).
  const az=((at%width+.5)/width-.5)*Math.PI*2,el=(.5-(Math.floor(at/width)+.5)/height)*Math.PI;
  return new T.Vector3(Math.cos(el)*Math.cos(az),Math.max(Math.sin(el),.35),Math.cos(el)*Math.sin(az)).normalize();
 }
 async function useEnvironment(name){
  if(!environments[name]){const texture=await hdrLoader.loadAsync(ENVIRONMENTS[name]);texture.mapping=T.EquirectangularReflectionMapping;environments[name]={texture,sun:brightestDirection(texture)};}
  envName=name;scene.environment=environments[name].texture;if(scene.background)scene.background=scene.environment;
  for(const b of document.querySelectorAll('[data-env]'))b.setAttribute('aria-pressed',String(b.dataset.env===name));
  rotateLights(lightAngle);
 }
 function rotateLights(degrees){
  lightAngle=((degrees%360)+360)%360;const r=T.MathUtils.degToRad(lightAngle);
  scene.environmentRotation.y=scene.backgroundRotation.y=r;
  if(environments[envName])key.position.copy(environments[envName].sun).applyAxisAngle(new T.Vector3(0,1,0),r).multiplyScalar(2.5);
  const slider=document.querySelector('#light-rotation');slider.value=String(Math.round(lightAngle));document.querySelector('#light-angle').textContent=Math.round(lightAngle)+'°';
 }
 await useEnvironment('studio');
 for(const b of document.querySelectorAll('[data-env]'))b.onclick=()=>useEnvironment(b.dataset.env);
 document.querySelector('#light-rotation').oninput=e=>rotateLights(Number(e.target.value));
 document.querySelector('#backdrop').onclick=e=>{const on=!scene.background;scene.background=on?scene.environment:null;scene.backgroundBlurriness=.35;scene.backgroundIntensity=.6;e.currentTarget.setAttribute('aria-pressed',String(on));};
 // Shift-drag on the stage turns the lights instead of the camera.
 let lightDrag=null;
 stage.addEventListener('pointerdown',e=>{if(!e.shiftKey)return;lightDrag={x:e.clientX,angle:lightAngle};controls.enabled=false;},{capture:true});
 addEventListener('pointermove',e=>{if(lightDrag)rotateLights(lightDrag.angle+(e.clientX-lightDrag.x)*.5);});
 addEventListener('pointerup',()=>{if(lightDrag){lightDrag=null;controls.enabled=true;}});

 const source=await loadModel();
 model=normalize(source.root);parts=source.parts;sockets=source.sockets;scene.add(model);
 // Clone materials so highlighting and wireframe only touch this model's meshes.
 model.traverse(o=>{if(o.isMesh)o.material=o.material.clone();});
 const box=new T.Box3().setFromObject(model);
 const floor=new T.Mesh(new T.PlaneGeometry(4,4),new T.ShadowMaterial({opacity:.28}));floor.rotation.x=-Math.PI/2;floor.position.y=box.min.y-.002;floor.receiveShadow=true;scene.add(floor);


 // Slots: each gets a container at its mount point (model space, meters). The source part moves
 // into the container's "original" group so poses, rail offsets and swaps act on one object.
 const materials={};model.traverse(o=>{if(o.isMesh&&!materials[o.material.name])materials[o.material.name]=o.material;});
 for(const spec of SLOTS){
  const socket=sockets.find(s=>s.userData.id===spec.id),part=parts.find(p=>p.id===spec.id);
  if(!socket||!part)continue;
  const container=new T.Group();container.name='slot:'+spec.id;model.add(container);
  container.position.copy(model.worldToLocal(socket.getWorldPosition(new T.Vector3())));
  const original=new T.Group();container.add(original);
  const nodes=part.nodes.map(n=>model.getObjectByName(T.PropertyBinding.sanitizeNodeName(n))).filter(Boolean);
  for(const node of nodes)original.attach(node);
  const home=new Map(nodes.map(n=>[n,n.position.clone()]));
  const options=spec.options.map(o=>{
   let object=null;
   if(o.build){object=o.build({original,materials,T});object.traverse(m=>{if(m.isMesh){m.castShadow=m.receiveShadow=true;m.material=m.material.clone();}});object.visible=false;container.add(object);}
   return {...o,object};
  });
  // Every mesh the slot can show belongs to its part, so clicks and highlights cover attachments too.
  part.objects=[];container.traverse(m=>{if(m.isMesh)part.objects.push(m);});
  slots[spec.id]={spec,container,original,home,options,part,direction:socket.userData.direction.clone().transformDirection(socket.matrixWorld),base:container.position.clone(),offset:0,baseDetail:part.detail};
 }
 function applySlot(id,optionId,offset,animate=false){
  const slot=slots[id],option=slot.options.find(o=>o.id===optionId)||slot.options[0];
  const shownBefore=slot.original.visible?slot.original:slot.options.find(o=>o.object?.visible)?.object;
  const before={container:slot.container.position.clone(),position:slot.original.position.clone(),rotationY:slot.original.rotation.y,nodes:new Map([...slot.home.keys()].map(n=>[n,n.position.clone()]))};
  build[id]=option.id;
  slot.original.visible=!!option.original;
  slot.original.rotation.set(0,option.pose?.rotationY||0,0);
  slot.original.position.set(...(option.pose?.position||[0,0,0]));
  for(const [node,p] of slot.home){node.position.copy(p);const d=option.pose?.nodes?.[Object.keys(option.pose.nodes).find(n=>T.PropertyBinding.sanitizeNodeName(n)===node.name)];if(d)node.position.add(new T.Vector3(...d));}
  for(const o of slot.options)if(o.object)o.object.visible=o===option;
  if(slot.spec.rail&&offset!==undefined){const {min,max,step}=slot.spec.rail;slot.offset=Math.round(T.MathUtils.clamp(offset,min,max)/step)*step;}
  slot.container.position.copy(slot.base).x+=slot.offset;
  slot.part.detail=option.detail||slot.baseDetail;
  slot.part.entry?.querySelector('span')&&(slot.part.entry.querySelector('span').textContent=option.label);
  if(selected===id)detail.textContent=slot.part.detail;
  renderBuild();updateStats();writeHash();
  if(!animate)return;
  // Stats above used the final pose; now rewind to the old one and glide there.
  const shown=option.original?slot.original:option.object,slide=slot.direction.clone().multiplyScalar(.05);
  tween(slot.container,'position',before.container,slot.container.position.clone());
  if(shown&&shown!==shownBefore)tween(shown,'position',shown.position.clone().add(slide),shown.position.clone());
  else if(shown===slot.original){
   tween(slot.original,'position',before.position,slot.original.position.clone());
   tween(slot.original,'rotationY',before.rotationY,slot.original.rotation.y);
   for(const [node,p] of before.nodes)tween(node,'position',p,node.position.clone());
  }
 }
 function tween(object,property,from,to){
  tweens=tweens.filter(t=>!(t.object===object&&t.property===property));
  const same=property==='rotationY'?from===to:from.equals(to);
  if(!same)tweens.push({object,property,from,to,t:0});
 }
 function stepTweens(dt){
  for(const t of tweens){
   t.t=Math.min(1,t.t+dt/.4);const e=1-(1-t.t)**3;
   if(t.property==='rotationY')t.object.rotation.y=t.from+(t.to-t.from)*e;else t.object.position.lerpVectors(t.from,t.to,e);
  }
  tweens=tweens.filter(t=>t.t<1);
 }
 document.querySelector('#source').innerHTML=`Model: <a href="${SOURCE_URL}">low-poly AK-74M Zenitco</a> by <a href="${AUTHOR_URL}">D_U</a>, <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Loose rounds and spare magazine removed. Scaled to ${OVERALL_LENGTH*1000} mm.`;

 for(const part of parts){
  const entry=document.createElement('button');entry.className='part';entry.setAttribute('aria-pressed','false');
  entry.innerHTML='<strong></strong><span></span>';entry.querySelector('strong').textContent=part.label;
  entry.querySelector('span').textContent=slots[part.id]?slots[part.id].options.find(o=>o.id===build[part.id])?.label||'':'';
  entry.onclick=()=>select(part.id);document.querySelector('#parts').append(entry);part.entry=entry;
 }


 // Build panel: one chip row per slot, plus rail position steppers.
 const buildPanel=document.querySelector('#build');
 function renderBuild(){
  buildPanel.replaceChildren(...Object.values(slots).map(slot=>{
   const row=document.createElement('div');row.className='slot';
   const head=document.createElement('div');head.className='slot-head';head.innerHTML='<span></span>';head.firstChild.textContent=slot.spec.label;
   const current=slot.options.find(o=>o.id===build[slot.spec.id]);
   if(slot.spec.rail&&(current.original||current.build)){
    const {min,max,step}=slot.spec.rail,stepper=document.createElement('span');stepper.className='stepper';
    const mm=Math.round(slot.offset*1000);
    for(const [text,delta,label] of [['−',-step,'rearward'],[`${mm>0?'+':''}${mm} mm`,0],['+',step,'forward']]){
     if(!delta){const out=document.createElement('output');out.textContent=text;stepper.append(out);continue;}
     const b=document.createElement('button');b.textContent=text;b.setAttribute('aria-label',`Move ${slot.spec.label.toLowerCase()} ${label} one rail slot`);
     b.disabled=delta<0?slot.offset<=min+1e-6:slot.offset>=max-1e-6;b.onclick=()=>{applySlot(slot.spec.id,build[slot.spec.id],slot.offset+delta,true);frame(slot.spec.id);};stepper.append(b);
    }
    head.append(stepper);
   }
   const chips=document.createElement('div');chips.className='chips';chips.role='group';chips.setAttribute('aria-label',slot.spec.label);
   for(const o of slot.options){const b=document.createElement('button');b.textContent=o.label;b.setAttribute('aria-pressed',String(build[slot.spec.id]===o.id));b.onclick=()=>{applySlot(slot.spec.id,o.id,undefined,true);frame(slot.spec.id);};chips.append(b);}
   row.append(head,chips);return row;
  }));
 }
 // Glide the camera toward a changed slot, keeping the current viewing direction.
 function frame(id){
  const target=slots[id].container.getWorldPosition(new T.Vector3());
  const dir=camera.position.clone().sub(controls.target).normalize();
  const distance=Math.min(camera.position.distanceTo(controls.target),.75);
  cameraMove={t:0,fromTarget:controls.target.clone(),fromPosition:camera.position.clone(),toTarget:target,toPosition:target.clone().addScaledVector(dir,distance)};
 }

 // Finishes recolour only black-finish and polymer surfaces of a part, including its attachments.
 const RECOLOURED=new Set(['h-190','polymer']);
 function applyFinish(partId,finishId){
  const part=parts.find(p=>p.id===partId),choice=FINISHES.find(f=>f.id===finishId)||FINISHES[0];
  finish[partId]=choice.id;
  for(const mesh of part.objects){const m=mesh.material;if(!RECOLOURED.has(m.name))continue;m.userData.baseColor??=m.color.clone();m.color.copy(choice.color?new T.Color(choice.color):m.userData.baseColor);}
  renderFinish();writeHash();
 }
 const finishPanel=document.querySelector('#finish');
 function renderFinish(){
  finishPanel.replaceChildren(...FINISH_PARTS.map(id=>parts.find(p=>p.id===id)).filter(Boolean).map(part=>{
   const row=document.createElement('div');row.className='finish-row';row.textContent=part.label;
   const swatches=document.createElement('div');swatches.className='swatches';swatches.role='group';swatches.setAttribute('aria-label',part.label+' colour');
   for(const f of FINISHES){const b=document.createElement('button');b.title=f.label;b.setAttribute('aria-label',f.label);b.setAttribute('aria-pressed',String(finish[part.id]===f.id));b.style.background=f.color||'linear-gradient(135deg,#1c1d1f 50%,#3a3c3f 50%)';b.onclick=()=>applyFinish(part.id,f.id);swatches.append(b);}
   row.append(swatches);return row;
  }));
 }
 // Live stats: length from the visible geometry (turntable angle ignored), mass from the registry.
 const statsPanel=document.querySelector('#stats');
 function updateStats(){
  const turned=model.rotation.y;model.rotation.y=0;model.updateMatrixWorld(true);
  const box=new T.Box3();model.traverseVisible(o=>{if(o.isMesh)box.expandByObject(o);});
  model.rotation.y=turned;model.updateMatrixWorld(true);buildBox=box;
  const grams=BASE_GRAMS+Object.values(slots).reduce((sum,slot)=>sum+(slot.options.find(o=>o.id===build[slot.spec.id])?.grams||0),0);
  statsPanel.innerHTML=`<div>Overall length<strong>${Math.round((box.max.x-box.min.x)*1000)} mm</strong></div><div>Weight, empty (illustrative)<strong>${(grams/1000).toFixed(2)} kg</strong></div>`;
 }
 // Build codes live in the URL hash, e.g. #muzzle=can&optic=scope@-20&stock-finish=fde
 let restoring=true;
 function writeHash(){
  if(restoring)return;
  // Ids and offsets are URL-safe, so the hash is joined by hand to keep '@' readable.
  const params=[];
  for(const slot of Object.values(slots)){const id=slot.spec.id;if(build[id]!==slot.options[0].id||slot.offset)params.push(id+'='+build[id]+(slot.offset?'@'+Math.round(slot.offset*1000):''));}
  for(const [id,f] of Object.entries(finish))if(f!==FINISHES[0].id)params.push(id+'-finish='+f);
  history.replaceState(null,'',params.length?'#'+params.join('&'):location.pathname+location.search);
 }
 function restore(hash){
  restoring=true;tweens=[];const params=new URLSearchParams(hash.replace(/^#/,''));
  for(const slot of Object.values(slots)){const [option,mm]=(params.get(slot.spec.id)||'').split('@');slot.offset=0;build[slot.spec.id]=slot.options.some(o=>o.id===option)?option:slot.options[0].id;slot.pendingOffset=Number(mm)/1000||0;}
  for(const id of Object.keys(slots))applySlot(id,build[id],slots[id].pendingOffset);
  for(const id of FINISH_PARTS)if(parts.some(p=>p.id===id))applyFinish(id,params.get(id+'-finish'));
  restoring=false;writeHash();
 }
 document.querySelector('#reset').onclick=()=>{restore('');view('three');};
 document.querySelector('#share').onclick=async e=>{const button=e.currentTarget;writeHash();try{await navigator.clipboard.writeText(location.href);button.textContent='Link copied';}catch{prompt('Copy this build link:',location.href);}setTimeout(()=>{button.textContent='Copy build link';},1600);};
 addEventListener('hashchange',()=>restore(location.hash));
 for(const id of Object.keys(slots))build[id]=slots[id].options[0].id;
 restore(location.hash);

 const socketLabels=sockets.map(s=>{const el=document.createElement('div');el.className='socket';el.textContent=s.userData.label;el.hidden=true;stage.append(el);return {socket:s,el};});
 const socketMarkers=new T.Group();socketMarkers.visible=false;scene.add(socketMarkers);
 for(const s of sockets){const ring=new T.Mesh(new T.TorusGeometry(.012,.0022,8,24),new T.MeshBasicMaterial({color:accent,depthTest:false}));ring.renderOrder=10;ring.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),s.userData.direction);s.getWorldPosition(ring.position);socketMarkers.add(ring);}
 const socketButton=document.querySelector('#sockets');
 if(!sockets.length){socketButton.disabled=true;socketButton.title='Mount points are calibrated in step 2';}
 socketButton.onclick=e=>{socketMarkers.visible=!socketMarkers.visible;e.currentTarget.setAttribute('aria-pressed',String(socketMarkers.visible));};
 document.querySelector('#spin').onclick=e=>{spinning=!spinning;e.currentTarget.setAttribute('aria-pressed',String(spinning));};
 document.querySelector('#wire').onclick=e=>{const on=e.currentTarget.getAttribute('aria-pressed')!=='true';model.traverse(o=>{if(o.isMesh)o.material.wireframe=on;});e.currentTarget.setAttribute('aria-pressed',String(on));};

 const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;
 function partAt(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(model,true)[0];return hit&&parts.find(p=>p.objects.includes(hit.object));}
 renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];cameraMove=null;});
 renderer.domElement.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5){const p=partAt(e);if(p)select(p.id);else if(selected)select(selected);}down=null;});
 renderer.domElement.addEventListener('pointermove',e=>{if(down||lightDrag)return;const p=partAt(e);renderer.domElement.style.cursor=p?'pointer':'';if((p?.id||null)!==hovered){hovered=p?.id||null;paint();}});
 renderer.domElement.addEventListener('pointerleave',()=>{if(hovered){hovered=null;paint();}});

 function view(name){
  cameraMove=null;
  // Fit the current build: long muzzle devices or a folded stock change the length.
  const center=buildBox.getCenter(new T.Vector3()),fit=(buildBox.max.x-buildBox.min.x)/OVERALL_LENGTH||1;
  const aspect=stage.clientWidth/stage.clientHeight,d=Math.max(1.3,1.6/aspect)*fit;
  controls.target.set(center.x,0,0);
  const at={three:[d*.55,d*.32,d*.8],left:[0,.02,-d],right:[0,.02,d],top:[0,d,.001],muzzle:[d*.65,.06,d*.28]}[name];
  if(name==='muzzle')controls.target.set(buildBox.max.x-.14,0,0);
  camera.position.set(...at).add(controls.target);controls.update();
 }
 const resize=()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);};
 new ResizeObserver(resize).observe(stage);resize();view('three');
 for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);
 stage.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected)select(selected);if(e.target!==stage)return;const v=camera.position.clone().sub(controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight')v.applyAxisAngle(new T.Vector3(0,1,0),e.key==='ArrowLeft'?.1:-.1);else if(e.key==='ArrowUp'||e.key==='ArrowDown')v.applyAxisAngle(new T.Vector3(1,0,0),e.key==='ArrowUp'?.1:-.1);else if(e.key==='+'||e.key==='=')v.multiplyScalar(.9);else if(e.key==='-')v.multiplyScalar(1.1);else return;e.preventDefault();camera.position.copy(controls.target).add(v);controls.update();});

 status.hidden=true;
 const clock=new T.Clock();
 renderer.setAnimationLoop(()=>{
  const dt=Math.min(clock.getDelta(),1/30);// cap so slow frames or background tabs never skip an animation
  if(spinning){model.rotation.y+=dt*.5;socketMarkers.rotation.y=model.rotation.y;}
  stepTweens(dt);
  if(cameraMove){cameraMove.t=Math.min(1,cameraMove.t+dt/.6);const e=1-(1-cameraMove.t)**3;controls.target.lerpVectors(cameraMove.fromTarget,cameraMove.toTarget,e);camera.position.lerpVectors(cameraMove.fromPosition,cameraMove.toPosition,e);if(cameraMove.t>=1)cameraMove=null;}
  controls.update();
  for(const {socket,el} of socketLabels){const p=socket.getWorldPosition(new T.Vector3()).project(camera);el.hidden=!socketMarkers.visible||p.z>1;el.style.left=(p.x*.5+.5)*stage.clientWidth+'px';el.style.top=(-p.y*.5+.5)*stage.clientHeight-18+'px';}
  renderer.render(scene,camera);
 });
}catch(err){console.error(err);status.textContent='The viewer could not load. Reload in a browser with WebGL enabled.';}
