import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {Music,TRACKS} from './music.js';
import {SLOTS,FINISHES,FINISH_TARGETS} from './attachments.js';
import {MODELS,DEFAULT_MODEL} from './models.js';
import {STATS,computeStats,blockedBy} from './stats.js';
import {OPERATOR_SECTIONS,OPERATOR_KEYS,DEFAULT_OPERATOR,buildOperator,disposeOperator,camoFor} from './operator.js';
import {shot,magOut,magIn} from './sfx.js';
import {DRILL,drillPlan,fireString,score,drawTarget} from './range.js';
import {POSES,applyPose,rifleFrame} from './field.js';

const accent=0xef8f39;
// Studio is generated by model-source/generate-studio-hdr.py; outdoor and sunset are Poly Haven
// "Quarry 01" and "Venice Sunset" (CC0).
const ENVIRONMENTS={studio:'./lighting/studio.hdr',outdoor:'./lighting/quarry_01_1k.hdr',sunset:'./lighting/venice_sunset_1k.hdr'};
// Launch look: the sunset HDR as a blurred backdrop, turned so the sun keys the rifle from front-left.
// Lights follow the camera, so this relationship holds from every angle; lightOffset is in degrees.
const LAUNCH={environment:'sunset',backdrop:true,lightOffset:255};
// The hero view the launch lighting was set up from: azimuth and elevation in radians.
const HERO={azimuth:-.2,elevation:.1};
// Hero angles per mode (radians): the rifle from just behind its right side; the operator from
// front-right; the field shot from the operator's right, where the rifle's right side faces.
const MODE_HERO={armoury:HERO,operator:{azimuth:-.45,elevation:.08},field:{azimuth:-1.05,elevation:.1}};
const MODES=['armoury','operator','field'];
// Reduced motion: camera moves and part swaps jump straight to their end state.
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
// Camera presets are sized for a rifle this long (m); longer or shorter builds scale them.
const FRAME_LENGTH=.943;

// Background music: on by default at 40% volume. It tries to start as the page opens, fading in
// slowly; where the browser blocks autoplay it starts on the first click or key press instead.
// The choice, track and volume persist per browser.
const music=new Music(),musicButton=document.querySelector('#music-toggle'),musicVolume=document.querySelector('#music-volume');
// v2: the default volume went up to 40%, so older saved settings are left behind.
const MUSIC_KEY='ak-customiser-music-v2';
const musicPrefs=(()=>{const base={on:true,volume:.4,track:TRACKS[0].id};try{return {...base,...JSON.parse(localStorage.getItem(MUSIC_KEY)||'{}')};}catch{return base;}})();
function saveMusic(){try{localStorage.setItem(MUSIC_KEY,JSON.stringify(musicPrefs));}catch{}}
function showMusic(){musicButton.setAttribute('aria-pressed',String(musicPrefs.on));for(const b of document.querySelectorAll('[data-track]'))b.setAttribute('aria-pressed',String(b.dataset.track===musicPrefs.track));musicVolume.value=String(Math.round(musicPrefs.volume*100));document.querySelector('#music-level').textContent=Math.round(musicPrefs.volume*100)+'%';}
if(!TRACKS.some(t=>t.id===musicPrefs.track))musicPrefs.track=TRACKS[0].id;
music.setVolume(musicPrefs.volume);music.setTrack(musicPrefs.track);showMusic();
const AUTOPLAY_FADE=1.5;
function stopWaiting(){removeEventListener('pointerdown',firstGesture,true);removeEventListener('keydown',firstGesture,true);}
function firstGesture(e){
 if(e.target===musicButton||e.target.closest?.('[data-track]'))return;
 stopWaiting();
 if(musicPrefs.on)music.start(AUTOPLAY_FADE);
}
addEventListener('pointerdown',firstGesture,true);addEventListener('keydown',firstGesture,true);
// Where autoplay is blocked, resume() stays pending until a gesture, so the listeners stay armed.
if(musicPrefs.on)music.start(AUTOPLAY_FADE).then(playing=>{if(playing)stopWaiting();});
// If music is on but the browser has not let it sound yet, ♪ starts it rather than switching it off.
musicButton.onclick=()=>{if(musicPrefs.on&&!music.audible()){stopWaiting();music.start(AUTOPLAY_FADE);return;}musicPrefs.on=!musicPrefs.on;musicPrefs.on?music.start():music.stop();stopWaiting();saveMusic();showMusic();};
// Picking a track also turns music on.
for(const b of document.querySelectorAll('[data-track]'))b.onclick=()=>{musicPrefs.track=b.dataset.track;music.setTrack(musicPrefs.track);if(!musicPrefs.on){musicPrefs.on=true;music.start();}saveMusic();showMusic();};
musicVolume.oninput=()=>{musicPrefs.volume=Number(musicVolume.value)/100;music.setVolume(musicPrefs.volume);saveMusic();showMusic();};

const stage=document.querySelector('#stage'),status=document.querySelector('#status'),detail=document.querySelector('#detail');
const buildPanel=document.querySelector('#build'),finishPanel=document.querySelector('#finish'),statsPanel=document.querySelector('#stats');
const scene=new T.Scene();
let renderer,camera,controls,selected=null,hovered=null,tweens=[],spinning=false,cameraMove=null,buildBox=new T.Box3(),restoring=true;
// Everything that belongs to the mounted rifle; replaced on a switch.
let rifle=null;
const socketMarkers=new T.Group();socketMarkers.visible=false;scene.add(socketMarkers);
const floor=new T.Mesh(new T.PlaneGeometry(4,4),new T.ShadowMaterial({opacity:.28}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);

// Lay the longest axis along x with the muzzle (the slimmer end) at +x, scale to meters, center.
function normalize(root,scale){
 root.updateMatrixWorld(true);
 let size=new T.Box3().setFromObject(root).getSize(new T.Vector3());
 if(size.z>size.x&&size.z>=size.y)root.rotation.y=Math.PI/2;
 else if(size.y>size.x&&size.y>size.z)root.rotation.z=Math.PI/2;
 root.updateMatrixWorld(true);
 const bounds=new T.Box3().setFromObject(root);size=bounds.getSize(new T.Vector3());
 const ends=[[Infinity,-Infinity],[Infinity,-Infinity]],v=new T.Vector3();
 root.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld);const t=(v.x-bounds.min.x)/size.x,e=t<.12?ends[0]:t>.88?ends[1]:null;if(e){e[0]=Math.min(e[0],v.y);e[1]=Math.max(e[1],v.y);}}});
 if(ends[0][1]-ends[0][0]<ends[1][1]-ends[1][0])root.rotateY(Math.PI);
 root.scale.multiplyScalar(scale);
 root.updateMatrixWorld(true);
 const center=new T.Box3().setFromObject(root).getCenter(new T.Vector3());
 const holder=new T.Group();holder.add(root);root.position.sub(center);return holder;
}

const nodeName=name=>T.PropertyBinding.sanitizeNodeName(name);
// Load a rifle and build its parts, slots (with library options) and finish targets.
async function loadRifle(id){
 const config=MODELS[id],root=(await new GLTFLoader().loadAsync(config.url)).scene;
 root.traverse(o=>{if(o.isMesh)o.castShadow=o.receiveShadow=true;});
 const sockets=config.sockets.map(([sid,label,p,d])=>{const o=new T.Object3D();o.name='socket:'+sid;o.position.set(...p);o.userData={id:sid,label,direction:new T.Vector3(...d)};root.add(o);return o;});
 const model=normalize(root,config.scale);
 // Clone materials so highlighting, finishes and wireframe only touch this rifle's meshes.
 model.traverse(o=>{if(o.isMesh)o.material=o.material.clone();});
 // A node claimed by one part is skipped when collecting another part's meshes.
 const claimed=new Set(config.parts.flatMap(p=>p.nodes.map(nodeName)));
 const parts=config.parts.map(p=>{
  const objects=[],own=new Set(p.nodes.map(nodeName));
  const walk=o=>{if(o.isMesh)objects.push(o);for(const c of o.children)if(!claimed.has(c.name)||own.has(c.name))walk(c);};
  for(const n of p.nodes){const node=model.getObjectByName(nodeName(n));if(node)walk(node);}
  return {...p,objects};
 });
 const materials={};model.traverse(o=>{if(o.isMesh&&!materials[o.material.name])materials[o.material.name]=o.material;});
 // Slots: a container at each mount point (model space, meters). The rifle's own part moves into
 // the container's "original" group so poses, rail offsets and swaps act on one object.
 const slots={};
 for(const spec of SLOTS){
  const socket=sockets.find(s=>s.userData.id===spec.id),part=parts.find(p=>p.id===spec.id),slotConfig=config.slots[spec.id];
  if(!socket||!part||!slotConfig)continue;
  const container=new T.Group();container.name='slot:'+spec.id;model.add(container);
  container.position.copy(model.worldToLocal(socket.getWorldPosition(new T.Vector3())));
  const original=new T.Group();container.add(original);
  const nodes=part.nodes.map(n=>model.getObjectByName(nodeName(n))).filter(Boolean);
  for(const node of nodes)original.attach(node);
  const home=new Map(nodes.map(n=>[n,n.position.clone()]));
  const library=slotConfig.library.map(entry=>{const o=typeof entry==='string'?{id:entry}:entry;return {...spec.library.find(l=>l.id===o.id),...o};});
  const options=[...slotConfig.factory,...library].map(o=>{
   let object=null;
   if(o.build){object=o.build({original,materials});object.traverse(m=>{if(m.isMesh){m.castShadow=m.receiveShadow=true;m.material=m.material.clone();}});object.visible=false;container.add(object);}
   return {...o,object};
  });
  // Every mesh the slot can show belongs to its part, so clicks and highlights cover attachments too.
  part.objects=[];container.traverse(m=>{if(m.isMesh)part.objects.push(m);});
  slots[spec.id]={spec,rail:slotConfig.rail,container,original,home,options,part,direction:socket.userData.direction.clone().transformDirection(socket.matrixWorld),base:container.position.clone(),offset:0,baseDetail:part.detail};
 }
 installCamo(model);
 // A finish target covers a whole part (attachments included) or one option's object only.
 const finishTargets=FINISH_TARGETS.map(t=>({...t,part:parts.find(p=>p.id===(t.part||t.id)),finishes:t.finishes||FINISHES}))
  .filter(t=>t.part&&(t.part.objects.length||t.option)&&(!t.option||slots[t.part.id]?.options.some(o=>o.id===t.option)));
 return {id,config,model,parts:parts.filter(p=>p.objects.length||slots[p.id]),sockets,slots,finishTargets,build:{},finish:{}};
}

function disposeRifle(r){
 r.model.removeFromParent();
 r.model.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});
 socketMarkers.clear();for(const l of r.socketLabels||[])l.el.remove();
 document.querySelector('#parts').replaceChildren();
}

// Selected parts glow orange; the part under the pointer gets a faint lift.
function paint(){
 if(!rifle)return;
 const chosen=new Set(rifle.parts.find(p=>p.id===selected)?.objects||[]),hover=new Set(rifle.parts.find(p=>p.id===hovered)?.objects||[]);
 rifle.model.traverse(o=>{if(!o.isMesh||!o.material.emissive)return;const on=chosen.has(o)||hover.has(o);o.material.emissive.setHex(chosen.has(o)?accent:on?0xffffff:0);o.material.emissiveIntensity=chosen.has(o)?.35:on?.06:0;});
}
function select(id){
 selected=selected===id?null:id;
 const part=rifle.parts.find(p=>p.id===selected);
 paint();
 for(const p of rifle.parts)p.entry.setAttribute('aria-pressed',String(p.id===selected));
 detail.textContent=part?part.detail:'Select a part on the model or in this list to highlight it.';
}

function applySlot(id,optionId,offset,animate=false){
 const slot=rifle.slots[id],option=slot.options.find(o=>o.id===optionId)||slot.options[0];
 const shownBefore=slot.original.visible?slot.original:slot.options.find(o=>o.object?.visible)?.object;
 const before={container:slot.container.position.clone(),position:slot.original.position.clone(),rotationY:slot.original.rotation.y,nodes:new Map([...slot.home.keys()].map(n=>[n,n.position.clone()]))};
 rifle.build[id]=option.id;
 slot.original.visible=!!option.original;
 slot.original.rotation.set(0,option.pose?.rotationY||0,0);
 slot.original.position.set(...(option.pose?.position||[0,0,0]));
 for(const [node,p] of slot.home){node.position.copy(p);const d=option.pose?.nodes?.[Object.keys(option.pose.nodes).find(n=>nodeName(n)===node.name)];if(d)node.position.add(new T.Vector3(...d));}
 for(const o of slot.options)if(o.object)o.object.visible=o===option;
 if(slot.rail&&offset!==undefined){const {min,max,step}=slot.rail;slot.offset=Math.round(T.MathUtils.clamp(offset,min,max)/step)*step;}
 if(!slot.rail)slot.offset=0;
 slot.container.position.copy(slot.base).x+=slot.offset;
 slot.part.detail=option.detail||slot.baseDetail;
 slot.part.entry?.querySelector('span')&&(slot.part.entry.querySelector('span').textContent=option.label);
 if(selected===id)detail.textContent=slot.part.detail;
 renderBuild();renderFinish();updateStats();writeHash();
 if(!animate)return;
 // Stats above used the final pose; now rewind to the old one and glide there.
 const shown=option.original?slot.original:option.object,slide=slot.direction.clone().multiplyScalar(.05);
 tween(slot.container,'position',before.container,slot.container.position.clone());
 if(shown&&shown!==shownBefore)tween(shown,'position',shown.position.clone().add(slide),shown.position.clone());
 else if(shown===slot.original){
  tween(slot.original,'position',before.position,slot.original.position.clone());
  tween(slot.original,'rotationY',before.rotationY,slot.original.rotation.y);
  for(const [node,p] of before.nodes)tween(node,'position',p,node.position.clone());
 }
}
function tween(object,property,from,to){
 tweens=tweens.filter(t=>!(t.object===object&&t.property===property));
 const same=property==='rotationY'?from===to:from.equals(to);
 if(!same)tweens.push({object,property,from,to,t:0});
}
function stepTweens(dt){
 for(const t of tweens){
  t.t=reduceMotion?1:Math.min(1,t.t+dt/.4);const e=1-(1-t.t)**3;
  if(t.property==='rotationY')t.object.rotation.y=t.from+(t.to-t.from)*e;else t.object.position.lerpVectors(t.from,t.to,e);
 }
 tweens=tweens.filter(t=>t.t<1);
}

// Build panel: one chip row per slot, plus rail position steppers.
function renderBuild(){
 if(restoring)return;
 buildPanel.replaceChildren(...Object.values(rifle.slots).map(slot=>{
  const row=document.createElement('div');row.className='slot';
  const head=document.createElement('div');head.className='slot-head';head.innerHTML='<span></span>';head.firstChild.textContent=slot.spec.label;
  const current=slot.options.find(o=>o.id===rifle.build[slot.spec.id]);
  if(slot.rail&&(current.original||current.build)){
   const {min,max,step}=slot.rail,stepper=document.createElement('span');stepper.className='stepper';
   const mm=Math.round(slot.offset*1000);
   for(const [text,delta,label] of [['−',-step,'rearward'],[`${mm>0?'+':''}${mm} mm`,0],['+',step,'forward']]){
    if(!delta){const out=document.createElement('output');out.textContent=text;stepper.append(out);continue;}
    const b=document.createElement('button');b.textContent=text;b.setAttribute('aria-label',`Move ${slot.spec.label.toLowerCase()} ${label} one rail slot`);
    b.disabled=delta<0?slot.offset<=min+1e-6:slot.offset>=max-1e-6;b.onclick=()=>{applySlot(slot.spec.id,rifle.build[slot.spec.id],slot.offset+delta,true);frame(slot.spec.id);};stepper.append(b);
   }
   head.append(stepper);
  }
  const chips=document.createElement('div');chips.className='chips';chips.role='group';chips.setAttribute('aria-label',slot.spec.label);
  for(const o of slot.options){
   const b=document.createElement('button');b.textContent=o.label;b.setAttribute('aria-pressed',String(rifle.build[slot.spec.id]===o.id));
   // Blocked options stay visible; clicking explains why instead of fitting them.
   const rule=blockedBy(rifle.build,slot.spec.id,o.id);
   if(rule){b.setAttribute('aria-disabled','true');b.classList.add('blocked');b.title=rule.reason;}
   b.onclick=()=>{if(rule){detail.textContent=`${o.label} can't be fitted: ${rule.reason}`;detail.classList.remove('flash');void detail.offsetWidth;detail.classList.add('flash');return;}applySlot(slot.spec.id,o.id,undefined,true);frame(slot.spec.id);};
   // Hover or focus previews the stat change this option would make.
   const preview=()=>renderStats({...rifle.build,[slot.spec.id]:o.id});
   b.onpointerenter=b.onfocus=preview;b.onpointerleave=b.onblur=()=>renderStats();
   chips.append(b);
  }
  row.append(head,chips);return row;
 }));
}
// Snap to the slot's hero angle (slot.spec.camera: direction from the part, distance in m,
// aim offset toward the part's middle), turned with the model so it works mid-turntable.
function frame(id){
 const slot=rifle.slots[id],target=slot.container.getWorldPosition(new T.Vector3());
 const {direction,distance,aim=[0,0,0]}=slot.spec.camera,up=new T.Vector3(0,1,0);
 target.add(new T.Vector3(...aim).applyAxisAngle(up,rifle.model.rotation.y));
 const dir=new T.Vector3(...direction).normalize().applyAxisAngle(up,rifle.model.rotation.y);
 cameraMove={t:0,fromTarget:controls.target.clone(),fromPosition:camera.position.clone(),toTarget:target,toPosition:target.clone().addScaledVector(dir,distance)};
}

// Camo on the rifle: it has no UVs, so recolourable materials get a triplanar projection in the
// rifle's own space (fixed per part at load, so the pattern stays glued to each part).
const CAMO_SCALE=4;// texture repeats per meter
function installCamo(model){
 model.updateMatrixWorld(true);const inverse=model.matrixWorld.clone().invert();
 model.traverse(o=>{
  if(!o.isMesh||!RECOLOURED.has(o.material.name))return;
  const uniforms={camoMap:{value:null},camoOn:{value:0},camoMatrix:{value:inverse.clone().multiply(o.matrixWorld)}};
  o.material.userData.camo=uniforms;
  o.material.onBeforeCompile=shader=>{
   Object.assign(shader.uniforms,uniforms);
   shader.vertexShader='uniform mat4 camoMatrix;\nvarying vec3 vCamoPos;\nvarying vec3 vCamoNormal;\n'+shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n vCamoPos=(camoMatrix*vec4(position,1.)).xyz;vCamoNormal=normalize(mat3(camoMatrix)*normal);');
   shader.fragmentShader='uniform sampler2D camoMap;\nuniform float camoOn;\nvarying vec3 vCamoPos;\nvarying vec3 vCamoNormal;\n'+shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
 if(camoOn>.5){vec3 n=pow(abs(normalize(vCamoNormal)),vec3(4.));n/=n.x+n.y+n.z;vec3 p=vCamoPos*${CAMO_SCALE.toFixed(1)};
  diffuseColor.rgb=texture2D(camoMap,p.yz).rgb*n.x+texture2D(camoMap,p.xz).rgb*n.y+texture2D(camoMap,p.xy).rgb*n.z;}`);
  };
  o.material.customProgramCacheKey=()=>'rifle-camo-v1';o.material.needsUpdate=true;
 });
}
// Finishes recolour only black-finish and polymer surfaces.
const RECOLOURED=new Set(['h-190','polymer']);
function targetMeshes(target){
 if(!target.option)return target.part.objects;
 const meshes=[];rifle.slots[target.part.id].options.find(o=>o.id===target.option).object.traverse(m=>{if(m.isMesh)meshes.push(m);});return meshes;
}
function applyFinish(targetId,finishId){
 const target=rifle.finishTargets.find(t=>t.id===targetId),choice=target.finishes.find(f=>f.id===finishId)||target.finishes[0];
 rifle.finish[targetId]=choice.id;
 for(const mesh of targetMeshes(target)){
  const m=mesh.material;if(!RECOLOURED.has(m.name))continue;m.userData.baseColor??=m.color.clone();
  m.color.copy(choice.color?new T.Color(choice.color):m.userData.baseColor);
  if(m.userData.camo){m.userData.camo.camoOn.value=choice.pattern?1:0;m.userData.camo.camoMap.value=choice.pattern?camoFor(choice.pattern):null;}
 }
 renderFinish();writeHash();
}
function renderFinish(){
 if(restoring)return;
 finishPanel.replaceChildren(...rifle.finishTargets.filter(t=>!t.option||rifle.build[t.part.id]===t.option).map(target=>{
  const label=target.label||target.part.label;
  const row=document.createElement('div');row.className='finish-row';row.textContent=label;
  const swatches=document.createElement('div');swatches.className='swatches';swatches.role='group';swatches.setAttribute('aria-label',label+' colour');
  for(const f of target.finishes){const b=document.createElement('button');b.title=f.label;b.setAttribute('aria-label',f.label);b.setAttribute('aria-pressed',String(rifle.finish[target.id]===f.id));b.style.background=f.color||'linear-gradient(135deg,#1c1d1f 50%,#3a3c3f 50%)';if(f.pattern)b.classList.add('pattern');b.onclick=()=>applyFinish(target.id,f.id);swatches.append(b);}
  row.append(swatches);return row;
 }));
}
// Live stats: length from the visible geometry (turntable angle ignored), mass and handling from
// the options (stats.js). renderStats(preview) shows the change a hovered option would make.
function updateStats(){buildBox=localBox(rifle.model);renderStats();}
// Bounds of an object's visible meshes in its own space, whatever its parent, pose or visibility.
function localBox(object){
 object.updateMatrixWorld(true);
 const inverse=object.matrixWorld.clone().invert(),box=new T.Box3(),m=new T.Matrix4();
 for(const child of object.children)child.traverseVisible(o=>{if(!o.isMesh)return;if(!o.geometry.boundingBox)o.geometry.computeBoundingBox();box.union(o.geometry.boundingBox.clone().applyMatrix4(m.multiplyMatrices(inverse,o.matrixWorld)));});
 return box;
}
function buildSummary(build){
 const options=Object.fromEntries(Object.values(rifle.slots).map(slot=>[slot.spec.id,slot.options.find(o=>o.id===build[slot.spec.id])]));
 const grams=rifle.config.baseGrams+Object.values(options).reduce((sum,o)=>sum+(o?.grams||0),0);
 return {grams,...computeStats(rifle.config.stats,options)};
}
function renderStats(preview){
 if(restoring)return;
 const now=buildSummary(rifle.build),next=preview?buildSummary(preview):now;
 const delta=(a,b,better)=>{if(a===b)return '';const good=better==='low'?b<a:b>a;return `<em class="${good?'up':'down'}">${b>a?'+':''}${b-a}</em>`;};
 const kg=g=>(g/1000).toFixed(2);
 const tiles=[
  ['Overall length',`${Math.round((buildBox.max.x-buildBox.min.x)*1000)} mm`,''],
  ['Weight, empty',`${kg(next.grams)} kg`,next.grams!==now.grams?`<em class="${next.grams<now.grams?'up':'down'}">${next.grams>now.grams?'+':''}${kg(next.grams-now.grams)}</em>`:''],
  ['Capacity',`${next.rounds} rds`,delta(now.rounds,next.rounds,'high')]
 ];
 statsPanel.innerHTML=tiles.map(([k,v,d])=>`<div class="tile">${k}<strong>${v}${d}</strong></div>`).join('')+
  '<div class="bars">'+STATS.map(s=>{
   const a=now[s.id],b=next[s.id],lo=Math.min(a,b),hi=Math.max(a,b),good=s.better==='low'?b<a:b>a;
   return `<div class="bar" title="${s.hint}${s.better==='low'?' Lower is better.':''}"><span>${s.label}</span><b>${b}${delta(a,b,s.better)}</b><i><u style="width:${lo}%"></u>${hi>lo?`<s class="${good?'up':'down'}" style="left:${lo}%;width:${hi-lo}%"></s>`:''}</i></div>`;
  }).join('')+'</div>';
}

// The rifle's launch build and colours (models.js `defaults`).
const defaultOption=slot=>{const id=rifle.config.defaults?.build?.[slot.spec.id];return slot.options.some(o=>o.id===id)?id:slot.options[0].id;};
const defaultFinish=target=>rifle.config.defaults?.finish?.[target.id]??'original';
// Loadout codes live in the URL hash, e.g. #mode=field&rifle=ak15k&optic=scope@-20&stock-finish=fde&o.headgear=helmet
function writeHash(){
 if(restoring)return;
 // Ids and offsets are URL-safe, so the hash is joined by hand to keep '@' readable.
 const params=rifle.id===DEFAULT_MODEL?[]:['rifle='+rifle.id];
 if(mode!=='armoury')params.unshift('mode='+mode);
 if(pose!=='aim')params.push('pose='+pose);
 for(const k of OPERATOR_KEYS)if(opState[k]!==DEFAULT_OPERATOR[k])params.push('o.'+k+'='+opState[k]);
 for(const slot of Object.values(rifle.slots)){const id=slot.spec.id;if(rifle.build[id]!==defaultOption(slot)||slot.offset)params.push(id+'='+rifle.build[id]+(slot.offset?'@'+Math.round(slot.offset*1000):''));}
 for(const t of rifle.finishTargets)if(rifle.finish[t.id]!==defaultFinish(t))params.push(t.id+'-finish='+rifle.finish[t.id]);
 history.replaceState(null,'',params.length?'#'+params.join('&'):location.pathname+location.search);
}

// Swap in another rifle; the camera, lighting and music carry on untouched.
async function mount(id){
 if(rifle?.id===id)return;
 status.hidden=false;
 const next=await loadRifle(id);
 if(rifle)disposeRifle(rifle);
 rifle=next;selected=hovered=null;tweens=[];scene.add(rifle.model);
 const config=rifle.config;
 floor.position.y=new T.Box3().setFromObject(rifle.model).min.y-.002;
 for(const b of document.querySelectorAll('[data-rifle]'))b.setAttribute('aria-pressed',String(b.dataset.rifle===id));
 document.querySelector('#specs').replaceChildren(...config.specs.map(([k,v])=>{const row=document.createElement('div');row.className='spec';row.innerHTML='<span></span><strong></strong>';row.firstChild.textContent=k;row.lastChild.textContent=v;return row;}));
 document.querySelector('#source').innerHTML=`Model: <a href="${config.source.url}">${config.source.title}</a> by <a href="${config.author.url}">${config.author.name}</a>, <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Loose rounds and spare magazine removed.`;
 for(const part of rifle.parts){
  const entry=document.createElement('button');entry.className='part';entry.setAttribute('aria-pressed','false');
  entry.innerHTML='<strong></strong><span></span>';entry.querySelector('strong').textContent=part.label;
  entry.onclick=()=>select(part.id);document.querySelector('#parts').append(entry);part.entry=entry;
 }
 detail.textContent='Select a part on the model or in this list to highlight it.';
 rifle.socketLabels=rifle.sockets.map(s=>{const el=document.createElement('div');el.className='socket';el.textContent=s.userData.label;el.hidden=true;stage.append(el);return {socket:s,el};});
 socketMarkers.rotation.y=0;
 for(const s of rifle.sockets){const ring=new T.Mesh(new T.TorusGeometry(.012,.0022,8,24),new T.MeshBasicMaterial({color:accent,depthTest:false}));ring.renderOrder=10;ring.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),s.userData.direction);s.getWorldPosition(ring.position);socketMarkers.add(ring);}
 if(document.querySelector('#wire').getAttribute('aria-pressed')==='true')rifle.model.traverse(o=>{if(o.isMesh)o.material.wireframe=true;});
 status.hidden=true;
}
// Restores are queued so rapid switches or hash changes apply in order.
let queue=Promise.resolve();
function restore(hash){
 const params=new URLSearchParams(hash.replace(/^#/,''));
 const id=MODELS[params.get('rifle')]?params.get('rifle'):DEFAULT_MODEL;
 queue=queue.then(async()=>{
  const switching=rifle?.id!==id;
  await mount(id);
  restoring=true;tweens=[];
  for(const slot of Object.values(rifle.slots)){const [option,mm]=(params.get(slot.spec.id)||'').split('@');slot.offset=0;rifle.build[slot.spec.id]=slot.options.some(o=>o.id===option)?option:defaultOption(slot);slot.pendingOffset=Number(mm)/1000||0;}
  // Old or hand-edited links may break a rule; the later slot falls back to its default.
  for(const slot of Object.values(rifle.slots)){const id=slot.spec.id;if(blockedBy(rifle.build,id,rifle.build[id]))rifle.build[id]=[defaultOption(slot),...slot.options.map(o=>o.id)].find(o=>!blockedBy(rifle.build,id,o));}
  for(const sid of Object.keys(rifle.slots))applySlot(sid,rifle.build[sid],rifle.slots[sid].pendingOffset);
  for(const t of rifle.finishTargets)applyFinish(t.id,params.get(t.id+'-finish')??defaultFinish(t));
  opState=readOperator(params);pose=POSES.some(p=>p.id===params.get('pose'))?params.get('pose'):'aim';
  const nextMode=MODES.includes(params.get('mode'))?params.get('mode'):'armoury';
  restoring=false;renderBuild();renderFinish();renderStats();renderOperatorPanel();renderPoses();
  const modeChanged=nextMode!==mode;mode=nextMode;applyMode();writeHash();
  if((switching||modeChanged)&&camera)view('hero');
 }).catch(err=>{console.error(err);status.hidden=false;status.textContent='The rifle could not load. Reload to try again.';});
 return queue;
}
// Switching rifles keeps whatever of the current build the other rifle can take.
function switchRifle(id){
 if(rifle?.id===id)return;
 const params=location.hash.replace(/^#/,'').split('&').filter(p=>p&&!p.startsWith('rifle='));
 if(id!==DEFAULT_MODEL)params.unshift('rifle='+id);
 restore('#'+params.join('&'));
}

function view(name){
 cameraMove=null;
 if(mode!=='armoury')return viewOperator(name);
 // Fit the current build: long muzzle devices, short carbines or a folded stock change the length.
 const center=buildBox.getCenter(new T.Vector3()),fit=(buildBox.max.x-buildBox.min.x)/FRAME_LENGTH||1;
 const aspect=stage.clientWidth/stage.clientHeight,d=Math.max(1.3,1.6/aspect)*fit;
 controls.target.set(center.x,0,0);
 const hero=new T.Vector3().setFromSphericalCoords(d*1.08,Math.PI/2-HERO.elevation,HERO.azimuth);
 const at={hero:hero.toArray(),three:[d*.55,d*.32,d*.8],left:[0,.02,-d],right:[0,.02,d],top:[0,d,.001],muzzle:[d*.65,.06,d*.28]}[name];
 if(name==='muzzle')controls.target.set(buildBox.max.x-.14,0,0);
 camera.position.set(...at).add(controls.target);controls.update();
}

// ---------- Operator and Field ----------
// mode: armoury (rifle on its own), operator (character creator) or field (operator holding the build).
let mode='armoury',pose='aim',opState={...DEFAULT_OPERATOR},operator=null,anchor=null,lastOpKey='',fieldFrame=null,reload=null;
function readOperator(params){
 const next={...DEFAULT_OPERATOR};
 for(const section of OPERATOR_SECTIONS)for(const c of section.controls){
  const v=params.get('o.'+c.id);if(v===null)continue;
  if(c.type==='range'){const n=Number(v);if(Number.isFinite(n))next[c.id]=T.MathUtils.clamp(n,c.min,c.max);}
  else if(c.options.some(o=>o.id===v))next[c.id]=v;
 }
 return next;
}
// Rebuild the operator when its state changed (cheap: a few dozen merged meshes).
function ensureOperator(){
 const key=JSON.stringify(opState);
 if(operator&&key===lastOpKey)return;
 const turned=operator?.root.rotation.y||0;
 if(rifle.model.parent===anchor)scene.add(rifle.model);
 if(operator){operator.root.removeFromParent();disposeOperator(operator);}
 operator=buildOperator(opState);lastOpKey=key;
 anchor=new T.Group();anchor.name='weapon anchor';operator.root.add(anchor);
 operator.root.position.y=floor.position.y;operator.root.rotation.y=turned;
 scene.add(operator.root);
}
// Show the right things for the mode and pose; the rifle moves between the scene and the operator's hands.
function applyMode(){
 if(kick){rifle.model.position.copy(kick.position);rifle.model.quaternion.copy(kick.quaternion);kick=null;}
 // A reload in progress is abandoned; the magazine goes back in the well.
 reload=null;const magSlot=rifle.slots.magazine;if(magSlot){magSlot.container.position.copy(magSlot.base);magSlot.container.visible=true;}
 for(const b of document.querySelectorAll('[data-mode]'))b.setAttribute('aria-selected',String(b.dataset.mode===mode));
 for(const panel of document.querySelectorAll('[data-panel]'))panel.hidden=!panel.dataset.panel.split(' ').includes(mode);
 document.querySelector('#title').innerHTML=mode==='armoury'?`${rifle.config.title},<br>low-poly.`:mode==='operator'?'Operator,<br>low-poly.':'In the field.';
 if(mode==='armoury'){
  fieldFrame=null;
  if(operator)operator.root.visible=false;
  if(rifle.model.parent!==scene)scene.add(rifle.model);
  rifle.model.position.set(0,0,0);rifle.model.quaternion.identity();rifle.model.visible=true;
  return;
 }
 ensureOperator();operator.root.visible=true;
 socketMarkers.visible=false;document.querySelector('#sockets').setAttribute('aria-pressed','false');
 if(selected)select(selected);
 if(mode==='operator'){if(rifle.model.parent!==scene)scene.add(rifle.model);rifle.model.visible=false;fieldFrame=null;applyPose(operator,'stand');return;}
 if(rifle.model.parent!==anchor)anchor.add(rifle.model);
 rifle.model.visible=true;
 fieldFrame=rifleFrame(rifle,buildBox);
 applyPose(operator,pose,rifle.model,fieldFrame,fieldMotion());
 document.querySelector('#pose-detail').textContent=POSES.find(p=>p.id===pose).detail;
}
function setMode(next){if(next===mode)return;mode=next;tweens=[];applyMode();writeHash();view('hero');}
function subjectBox(){
 const box=new T.Box3().setFromObject(operator.root);
 return box.isEmpty()?new T.Box3(new T.Vector3(-.3,0,-.3),new T.Vector3(.3,1.8,.3)):box;
}
function viewOperator(name){
 const box=subjectBox(),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());
 const aspect=stage.clientWidth/stage.clientHeight,d=Math.max(size.y*2.15,Math.max(size.x,size.z)*2.1/aspect,1.8);
 const hero=MODE_HERO[mode];
 controls.target.copy(center);
 const at={hero:new T.Vector3().setFromSphericalCoords(d,Math.PI/2-hero.elevation,hero.azimuth),three:new T.Vector3(.6,.3,.75).setLength(d),left:new T.Vector3(d,.1,0),right:new T.Vector3(-d,.1,0),top:new T.Vector3(0,d,.001),muzzle:new T.Vector3(-.35,.1,1).setLength(d*.6)}[name];
 camera.position.copy(center).add(at);controls.update();
}
// Snap toward the part of the operator a control changed.
function frameOperator(focus){
 if(!operator||focus==='full'){view('hero');return;}
 const J=operator.joints,s=operator.height/1.78;
 const spot={face:[J.head,[0,.1*s,0],[.35,.12,1],.75],torso:[J.chest,[0,.05,0],[.45,.15,1],1.35],arm:[J.upperArmL,[0,-.12,0],[1,.25,.55],.8]}[focus];
 if(!spot)return;
 const [joint,offset,dir,dist]=spot;
 const target=joint.localToWorld(new T.Vector3(...offset));
 const direction=new T.Vector3(...dir).normalize().applyAxisAngle(new T.Vector3(0,1,0),operator.root.rotation.y);
 cameraMove={t:0,fromTarget:controls.target.clone(),fromPosition:camera.position.clone(),toTarget:target,toPosition:target.clone().addScaledVector(direction,dist)};
}
// Operator panel, generated from OPERATOR_SECTIONS.
function setOperator(key,value,focus){
 opState={...opState,[key]:value};applyMode();renderOperatorPanel();writeHash();if(focus)frameOperator(focus);
}
function renderOperatorPanel(){
 const panel=document.querySelector('#operator-panel');
 panel.replaceChildren(...OPERATOR_SECTIONS.map(section=>{
  const wrap=document.createElement('div');wrap.className='op-section';
  const h=document.createElement('h2');h.textContent=section.label.toUpperCase();wrap.append(h);
  for(const c of section.controls){
   const row=document.createElement('div');row.className='slot';
   const head=document.createElement('div');head.className='slot-head';head.innerHTML='<span></span>';head.firstChild.textContent=c.label;row.append(head);
   if(c.type==='range'){
    const out=document.createElement('output');out.textContent=c.unit?opState[c.id].toFixed(2)+' '+c.unit:c.ends[opState[c.id]<.34?0:opState[c.id]>.66?1:0]+(opState[c.id]>=.34&&opState[c.id]<=.66?' · average':'');
    if(!c.unit)out.textContent=opState[c.id]<.34?c.ends[0]:opState[c.id]>.66?c.ends[1]:'Average';
    head.append(out);
    const input=document.createElement('input');input.type='range';input.min=c.min;input.max=c.max;input.step=c.step;input.value=opState[c.id];input.setAttribute('aria-label',c.label);input.className='op-range';
    input.oninput=()=>{opState={...opState,[c.id]:Number(input.value)};applyMode();out.textContent=c.unit?Number(input.value).toFixed(2)+' '+c.unit:Number(input.value)<.34?c.ends[0]:Number(input.value)>.66?c.ends[1]:'Average';};
    input.onchange=()=>{writeHash();view('hero');};
    row.append(input);
   }else{
    const group=document.createElement('div');group.className=c.type==='swatch'?'swatches op-swatches':'chips';group.role='group';group.setAttribute('aria-label',c.label);
    for(const o of c.options){
     const b=document.createElement('button');b.setAttribute('aria-pressed',String(opState[c.id]===o.id));
     if(c.type==='swatch'){b.title=o.label;b.setAttribute('aria-label',o.label);b.style.background=o.color||'repeating-linear-gradient(45deg,#2a3035 0 4px,#3a4147 4px 8px)';if(o.pattern)b.classList.add('pattern');}
     else b.textContent=o.label;
     b.onclick=()=>setOperator(c.id,o.id,section.camera);group.append(b);
    }
    row.append(group);
   }
   wrap.append(row);
  }
  return wrap;
 }));
}
function renderPoses(){
 const box=document.querySelector('#poses');
 box.replaceChildren(...POSES.map(p=>{const b=document.createElement('button');b.textContent=p.label;b.setAttribute('aria-pressed',String(p.id===pose));b.onclick=()=>{pose=p.id;renderPoses();applyMode();writeHash();};return b;}));
}
function randomOperator(){
 const next={};
 for(const section of OPERATOR_SECTIONS)for(const c of section.controls){
  if(c.type==='range')next[c.id]=Math.round((c.min+Math.random()*(c.max-c.min))/c.step)*c.step;
  else next[c.id]=c.options[Math.floor(Math.random()*c.options.length)].id;
 }
 next.height=Math.round(next.height*100)/100;
 return next;
}
// Presets: whole loadouts (rifle build, finishes, operator, pose) as hash fragments; the current
// screen is kept.
const PRESETS=[
 {id:'partisan',label:'Partisan',hash:''},
 {id:'scout',label:'Scout',hash:'rifle=ak15k&foregrip=stop&handguard-finish=od&foregrip-finish=od&grip-finish=od&stock-finish=od&magazine-finish=od&suppressor-finish=od&pose=patrol&o.headgear=boonie&o.faceCover=shemagh&o.top=smock&o.topColor=flora&o.vest=rig&o.gearColor=olive&o.pack=radio&o.facial=none&o.armband=none'},
 {id:'breacher',label:'Breacher',hash:'rifle=ak15k&muzzle=brake&optic=holo&magazine=60&stock=collapsed&handguard-finish=original&foregrip-finish=original&grip-finish=original&stock-finish=original&magazine-finish=original&pose=ready&o.headgear=helmet&o.faceCover=balaclava&o.eyewear=goggles&o.topColor=black&o.pantsColor=black&o.gloves=full&o.vest=plates&o.gearColor=black&o.facial=none&o.hair=buzz&o.armband=none&o.patch=shield'},
 {id:'marksman',label:'Marksman',hash:'optic=scope&foregrip=angled&handguard-finish=desert&stock-finish=desert&foregrip-finish=desert&suppressor-finish=fde&o.headgear=boonie&o.top=smock&o.topColor=desert&o.pantsColor=desert&o.gearColor=tan&o.eyewear=glasses&o.facial=moustache&o.armband=none'}
];
function applyPreset(preset){restore('#'+[mode!=='armoury'?'mode='+mode:'',preset.hash].filter(Boolean).join('&')).then(()=>view('hero'));}

// Test fire: an original synthesised shot shaped by the muzzle device, a muzzle flash (none when
// suppressed) and a recoil kick sized by the Recoil stat.
let kick=null;
const flash=new T.Group(),flashLight=new T.PointLight(0xffb060,0,1.5,2);
{const m=new T.MeshBasicMaterial({color:0xffc070,transparent:true,opacity:.9,blending:T.AdditiveBlending,depthWrite:false,side:T.DoubleSide});
 const petal=new T.ConeGeometry(.018,.09,5).rotateZ(-Math.PI/2).translate(.045,0,0);
 for(let i=0;i<3;i++){const p=new T.Mesh(petal,m);p.rotation.x=i*Math.PI/3;flash.add(p);}
 flash.add(flashLight);flash.visible=false;}
function testFire(){
 const muzzle=rifle.build.muzzle,holder=rifle.model;
 shot(muzzle);
 if(!holder.visible)return;
 if(muzzle!=='can'){
  holder.add(flash);flash.position.set(buildBox.max.x,rifle.slots.muzzle?.container.position.y??0,0);
  flash.scale.setScalar(.8+Math.random()*.5);flash.rotation.x=Math.random()*Math.PI;flash.visible=true;flashLight.intensity=3;
  setTimeout(()=>{flash.visible=false;flashLight.intensity=0;},55);
 }
 if(kick){holder.position.copy(kick.position);holder.quaternion.copy(kick.quaternion);}
 kick={t:0,position:holder.position.clone(),quaternion:holder.quaternion.clone(),strength:buildSummary(rifle.build).recoil/60};
}
// Kick curve: a sharp push back and up, then an exponential settle.
function kickOffset(){
 if(!kick)return null;
 const f=kick.t<.035?kick.t/.035:Math.exp(-(kick.t-.035)*12);
 return {back:.035*f*kick.strength,climb:.07*f*kick.strength};
}
function stepKick(dt){
 if(!kick)return;
 kick.t+=dt;const holder=rifle.model;
 // In the Field the pose applies the kick every frame; in the Armoury it moves the rifle directly.
 if(mode==='armoury'){
  const k=kickOffset();
  holder.position.copy(kick.position).add(new T.Vector3(-1,0,0).applyQuaternion(kick.quaternion).multiplyScalar(k.back));
  holder.quaternion.copy(kick.quaternion).multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),k.climb));
 }
 if(kick.t>.6){if(mode==='armoury'){holder.position.copy(kick.position);holder.quaternion.copy(kick.quaternion);}kick=null;}
}
// Per-frame Field motion: breathing and sway (bigger for heavy, awkward builds), kick and reload.
const clockStart=performance.now();
function fieldMotion(){
 const summary=buildSummary(rifle.build),kg=summary.grams/1000;
 const motion={t:reduceMotion?0:(performance.now()-clockStart)/1000,sway:reduceMotion?0:.002+kg*.0009+(100-summary.ergo)*.00005,kick:kickOffset()};
 if(reload)motion.reload=Math.min(1,reload.t/reload.duration);
 return motion;
}
// Reload: duration from Handling, longer for big magazines; sounds at the drop and the seat.
function startReload(){
 if(mode!=='field'||pose==='stand'||reload||rifle.build.magazine==='none')return;
 const summary=buildSummary(rifle.build),mag=rifle.build.magazine;
 const duration=T.MathUtils.clamp(2.2*(1+(60-summary.handling)/120)*(mag==='drum'?1.35:mag==='60'?1.15:1),1.4,3.6);
 reload={t:0,duration,cues:new Set()};
 document.querySelector('#pose-detail').textContent=`Reloading: ${duration.toFixed(1)} s with this build (Handling ${summary.handling}${mag==='drum'?', drum':''}).`;
}
function stepReload(dt){
 if(!reload)return;
 // body[data-reload] exposes progress (0–1) for tests.
 reload.t+=dt;document.body.dataset.reload=(reload.t/reload.duration).toFixed(2);const r=reload.t/reload.duration;
 if(r>.18&&!reload.cues.has('out')){reload.cues.add('out');magOut();}
 if(r>.66&&!reload.cues.has('in')){reload.cues.add('in');magIn();}
 if(r>=1){reload=null;delete document.body.dataset.reload;document.querySelector('#pose-detail').textContent=POSES.find(p=>p.id===pose).detail;}
}

// Range drill: switch to Aim, fire the string on the plan's timing (sound, flash, kick in the
// hands) and plot each hit on the target card as it lands.
let drill=null;
function startDrill(){
 if(mode!=='field'||drill)return;
 if(rifle.build.magazine==='none'){document.querySelector('#drill-result').textContent='Fit a magazine first.';return;}
 if(pose!=='aim'){pose='aim';renderPoses();applyMode();writeHash();}
 const summary=buildSummary(rifle.build),plan=drillPlan(summary,summary.grams/1000),shots=fireString(plan);
 drill={t:0,shots,next:0,result:score(shots)};
 const canvas=document.querySelector('#target');drawTarget(canvas,shots,0);
 document.querySelector('#drill-result').textContent=`Firing ${DRILL.rounds} rounds at ${DRILL.distance} m…`;
}
function stepDrill(dt){
 if(!drill)return;
 drill.t+=dt;
 while(drill.next<drill.shots.length&&drill.t>=drill.shots[drill.next].t){testFire();drill.next++;drawTarget(document.querySelector('#target'),drill.shots,drill.next);}
 if(drill.next>=drill.shots.length&&drill.t>drill.shots.at(-1).t+.4){
  const r=drill.result;
  document.querySelector('#drill-result').innerHTML=`<strong>${r.total}/${r.max}</strong> · group ${r.group.toFixed(1)} cm · ${r.time.toFixed(2)} s<br><span>${r.points.join(' · ')}</span>`;
  drill=null;
 }
}

// Loadout card: the current view on the left, stats, parts and the operator on the right.
function saveCard(){
 renderer.render(scene,camera);
 const W=1600,H=900,panel=560,out=document.createElement('canvas');out.width=W;out.height=H;const g=out.getContext('2d');
 const grad=g.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#3a454b');grad.addColorStop(1,'#1b2226');g.fillStyle=grad;g.fillRect(0,0,W-panel,H);
 // Cover-fit the render into the picture area.
 const src=renderer.domElement,area=W-panel,scale=Math.max(area/src.width,H/src.height),sw=area/scale,sh=H/scale;
 g.drawImage(src,(src.width-sw)/2,(src.height-sh)/2,sw,sh,0,0,area,H);
 g.fillStyle='#161d21';g.fillRect(area,0,panel,H);g.fillStyle='#ef8f39';g.fillRect(area,0,4,H);
 const x=area+44;let y=70;
 const text=(t,size,color='#eceeea',weight=400,font='system-ui,sans-serif')=>{g.fillStyle=color;g.font=`${weight} ${size}px ${font}`;g.fillText(t,x,y);};
 text('PARTISAN · LOADOUT',16,'#ef8f39',600,'ui-monospace,monospace');y+=48;
 text(rifle.config.title,34,'#eceeea',650);y+=34;
 const summary=buildSummary(rifle.build);
 text(`${Math.round((buildBox.max.x-buildBox.min.x)*1000)} mm · ${(summary.grams/1000).toFixed(2)} kg · ${summary.rounds} rds`,17,'#9aa9b0');y+=36;
 for(const st of STATS){
  text(st.label,15,'#9aa9b0');g.fillStyle='#eceeea';g.font='600 15px ui-monospace,monospace';g.fillText(String(summary[st.id]),x+panel-110,y);y+=10;
  g.fillStyle='#ffffff18';g.fillRect(x,y,panel-88,6);g.fillStyle='#c9cfd2';g.fillRect(x,y,(panel-88)*summary[st.id]/100,6);y+=26;
 }
 y+=8;text('BUILD',13,'#9aa9b0',600,'ui-monospace,monospace');y+=26;
 for(const slot of Object.values(rifle.slots)){const o=slot.options.find(o=>o.id===rifle.build[slot.spec.id]);text(`${slot.spec.label}: ${o.label}${slot.offset?` (${slot.offset>0?'+':''}${Math.round(slot.offset*1000)} mm)`:''}`,16);y+=25;}
 y+=12;text('OPERATOR',13,'#9aa9b0',600,'ui-monospace,monospace');y+=26;
 const label=(id)=>{for(const sec of OPERATOR_SECTIONS)for(const c of sec.controls)if(c.id===id)return c.options?.find(o=>o.id===opState[id])?.label??opState[id];};
 for(const line of [`${label('frame')}, ${opState.height.toFixed(2)} m · ${label('headgear')}`,`${label('top')} (${label('topColor')}) · ${label('pants')} (${label('pantsColor')})`,`${label('vest')} · ${label('pack')} · armband ${label('armband')}`]){text(line,16);y+=25;}
 y=H-40;text(location.href.replace(/^https?:\/\//,'').slice(0,64),12,'#6f7f86',400,'ui-monospace,monospace');
 const a=document.createElement('a');a.download=`partisan-loadout-${rifle.id}.png`;a.href=out.toDataURL('image/png');a.click();
}

// Photo: render the current view and stamp a caption strip, then download a PNG.
function savePhoto(){
 renderer.render(scene,camera);
 const src=renderer.domElement,out=document.createElement('canvas');out.width=src.width;out.height=src.height;
 const g=out.getContext('2d'),scale=src.width/1400;
 // The stage's own CSS backdrop isn't in the WebGL canvas, so paint a matching base first.
 const grad=g.createRadialGradient(out.width/2,out.height*.42,0,out.width/2,out.height*.42,out.width*.7);grad.addColorStop(0,'#3a454b');grad.addColorStop(1,'#1b2226');
 g.fillStyle=grad;g.fillRect(0,0,out.width,out.height);g.drawImage(src,0,0);
 const bar=Math.round(64*scale);g.fillStyle='#0f1417d9';g.fillRect(0,out.height-bar,out.width,bar);
 g.fillStyle='#ef8f39';g.font=`600 ${Math.round(22*scale)}px ui-monospace,monospace`;g.fillText('PARTISAN',Math.round(24*scale),out.height-bar/2+Math.round(8*scale));
 g.fillStyle='#eceeea';g.font=`${Math.round(18*scale)}px system-ui,sans-serif`;
 g.fillText(`${rifle.config.title} · ${POSES.find(p=>p.id===pose).label} · ${new Date().toISOString().slice(0,10)}`,Math.round(170*scale),out.height-bar/2+Math.round(7*scale));
 const a=document.createElement('a');a.download=`partisan-${rifle.id}-${pose}.png`;a.href=out.toDataURL('image/png');a.click();
}

try{
 renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;stage.prepend(renderer.domElement);
 camera=new T.PerspectiveCamera(35,1,.01,20);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.15;controls.maxDistance=3.5;controls.enablePan=true;

 // Image-based lighting from an HDR environment. The directional key only casts the shadow;
 // it is aimed at the HDR's brightest texel and turns with the environment.
 const key=new T.DirectionalLight(0xffffff,1.6);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-1.3,right:1.3,top:1.3,bottom:-1.3,near:.5,far:8});key.shadow.normalBias=.01;key.shadow.radius=4;scene.add(key);
 const hdrLoader=new RGBELoader().setDataType(T.FloatType),environments={};
 let envName=LAUNCH.environment,lightAngle=LAUNCH.lightOffset;
 function brightestDirection(texture){
  const {data,width,height}=texture.image;let best=-1,at=0;
  for(let i=0;i<width*height;i++){const l=data[i*4]*.2126+data[i*4+1]*.7152+data[i*4+2]*.0722;if(l>best){best=l;at=i;}}
  // Row 0 is the top of the equirect; azimuth follows three.js equirect UVs, atan2(z,x).
  const az=((at%width+.5)/width-.5)*Math.PI*2,el=(.5-(Math.floor(at/width)+.5)/height)*Math.PI;
  return new T.Vector3(Math.cos(el)*Math.cos(az),Math.max(Math.sin(el),.35),Math.cos(el)*Math.sin(az)).normalize();
 }
 async function useEnvironment(name){
  if(!environments[name]){const texture=await hdrLoader.loadAsync(ENVIRONMENTS[name]);texture.mapping=T.EquirectangularReflectionMapping;environments[name]={texture,sun:brightestDirection(texture)};}
  envName=name;scene.environment=environments[name].texture;if(scene.background)scene.background=scene.environment;
  for(const b of document.querySelectorAll('[data-env]'))b.setAttribute('aria-pressed',String(b.dataset.env===name));
 }
 // Environment, backdrop and shadow key turn with the camera's azimuth plus the user's offset,
 // so the lighting stays put relative to the view while orbiting. Runs every frame.
 function orientLights(){
  const r=controls.getAzimuthalAngle()-MODE_HERO[mode].azimuth+T.MathUtils.degToRad(lightAngle);
  scene.environmentRotation.y=scene.backgroundRotation.y=r;
  if(environments[envName])key.position.copy(environments[envName].sun).applyAxisAngle(new T.Vector3(0,1,0),r).multiplyScalar(3.5).add(key.target.position);
 }
 function rotateLights(degrees){
  lightAngle=((degrees%360)+360)%360;
  const slider=document.querySelector('#light-rotation');slider.value=String(Math.round(lightAngle));document.querySelector('#light-angle').textContent=Math.round(lightAngle)+'°';
 }
 await useEnvironment(envName);rotateLights(lightAngle);
 for(const b of document.querySelectorAll('[data-env]'))b.onclick=()=>useEnvironment(b.dataset.env);
 document.querySelector('#light-rotation').oninput=e=>rotateLights(Number(e.target.value));
 function setBackdrop(on){scene.background=on?scene.environment:null;scene.backgroundBlurriness=.5;scene.backgroundIntensity=.55;document.querySelector('#backdrop').setAttribute('aria-pressed',String(on));}
 setBackdrop(LAUNCH.backdrop);
 document.querySelector('#backdrop').onclick=()=>setBackdrop(!scene.background);
 // Alt-drag (the usual 3D-viewer gesture) or shift-drag on the stage turns the lights instead of the camera.
 let lightDrag=null;
 stage.addEventListener('pointerdown',e=>{if(!e.altKey&&!e.shiftKey)return;e.preventDefault();lightDrag={x:e.clientX,angle:lightAngle};controls.enabled=false;},{capture:true});
 addEventListener('pointermove',e=>{if(lightDrag)rotateLights(lightDrag.angle+(e.clientX-lightDrag.x)*.5);});
 addEventListener('pointerup',()=>{if(lightDrag){lightDrag=null;controls.enabled=true;}});

 const resize=()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);};
 new ResizeObserver(resize).observe(stage);resize();
 await restore(location.hash);
 if(!rifle)throw new Error('No rifle loaded');
 view('hero');
 for(const b of document.querySelectorAll('[data-rifle]'))b.onclick=()=>switchRifle(b.dataset.rifle);
 for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>setMode(b.dataset.mode);
 document.querySelector('#randomise').onclick=()=>{opState=randomOperator();applyMode();renderOperatorPanel();writeHash();view('hero');};
 document.querySelector('#operator-default').onclick=()=>{opState={...DEFAULT_OPERATOR};applyMode();renderOperatorPanel();writeHash();view('hero');};
 document.querySelector('#photo').onclick=savePhoto;
 document.querySelector('#card').onclick=saveCard;
 document.querySelector('#reload').onclick=startReload;
 document.querySelector('#drill').onclick=startDrill;
 drawTarget(document.querySelector('#target'),[],0);
 // First visit: a one-off hint, dismissed by its button or after 14 s; remembered per browser.
 {const hint=document.querySelector('#first-run');let seen=false;try{seen=!!localStorage.getItem('partisan-demo-seen');}catch{}
  if(!seen){hint.hidden=false;const close=()=>{hint.hidden=true;try{localStorage.setItem('partisan-demo-seen','1');}catch{}};hint.querySelector('button').onclick=close;setTimeout(close,14000);}}
 for(const b of document.querySelectorAll('.fire'))b.onclick=testFire;
 document.querySelector('#presets').replaceChildren(...PRESETS.map(p=>{const b=document.createElement('button');b.textContent=p.label;b.onclick=()=>applyPreset(p);return b;}));
 // Reset returns the rifle build to its defaults; mode, pose and operator stay.
 document.querySelector('#reset').onclick=()=>{const keep=location.hash.replace(/^#/,'').split('&').filter(p=>/^(rifle|mode|pose|o\.)/.test(p));restore(keep.length?'#'+keep.join('&'):'').then(()=>view('hero'));};
 document.querySelector('#share').onclick=async e=>{const button=e.currentTarget;writeHash();try{await navigator.clipboard.writeText(location.href);button.textContent='Link copied';}catch{prompt('Copy this loadout link:',location.href);}setTimeout(()=>{button.textContent='Copy loadout link';},1600);};
 addEventListener('hashchange',()=>restore(location.hash));

 document.querySelector('#sockets').onclick=e=>{socketMarkers.visible=!socketMarkers.visible;e.currentTarget.setAttribute('aria-pressed',String(socketMarkers.visible));};
 document.querySelector('#spin').onclick=e=>{spinning=!spinning;e.currentTarget.setAttribute('aria-pressed',String(spinning));};
 document.querySelector('#wire').onclick=e=>{const on=e.currentTarget.getAttribute('aria-pressed')!=='true';rifle.model.traverse(o=>{if(o.isMesh)o.material.wireframe=on;});e.currentTarget.setAttribute('aria-pressed',String(on));};

 const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;
 function partAt(e){if(mode!=='armoury')return null;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(rifle.model,true)[0];return hit&&rifle.parts.find(p=>p.objects.includes(hit.object));}
 renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];cameraMove=null;});
 renderer.domElement.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5){const p=partAt(e);if(p)select(p.id);else if(selected)select(selected);}down=null;});
 renderer.domElement.addEventListener('pointermove',e=>{if(down||lightDrag)return;const p=partAt(e);renderer.domElement.style.cursor=p?'pointer':'';if((p?.id||null)!==hovered){hovered=p?.id||null;paint();}});
 renderer.domElement.addEventListener('pointerleave',()=>{if(hovered){hovered=null;paint();}});

 for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);
 stage.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected)select(selected);if(e.target!==stage)return;const v=camera.position.clone().sub(controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight')v.applyAxisAngle(new T.Vector3(0,1,0),e.key==='ArrowLeft'?.1:-.1);else if(e.key==='ArrowUp'||e.key==='ArrowDown')v.applyAxisAngle(new T.Vector3(1,0,0),e.key==='ArrowUp'?.1:-.1);else if(e.key==='+'||e.key==='=')v.multiplyScalar(.9);else if(e.key==='-')v.multiplyScalar(1.1);else return;e.preventDefault();camera.position.copy(controls.target).add(v);controls.update();});

 const clock=new T.Clock();
 renderer.setAnimationLoop(()=>{
  const dt=Math.min(clock.getDelta(),1/30);// cap so slow frames or background tabs never skip an animation
  stepKick(dt);stepReload(dt);stepDrill(reduceMotion?1:dt);
  // The operator breathes and the Field pose re-solves every frame (sway, kick, reload).
  if(operator&&mode!=='armoury'){if(mode==='field'&&fieldFrame)applyPose(operator,pose,rifle.model,fieldFrame,fieldMotion());else applyPose(operator,'stand',null,null,{t:reduceMotion?0:(performance.now()-clockStart)/1000});}
  if(spinning&&!kick){if(mode==='armoury'){rifle.model.rotation.y+=dt*.5;socketMarkers.rotation.y=rifle.model.rotation.y;}else if(operator)operator.root.rotation.y+=dt*.5;}
  stepTweens(dt);
  if(cameraMove){cameraMove.t=reduceMotion?1:Math.min(1,cameraMove.t+dt/.45);const e=1-(1-cameraMove.t)**4;controls.target.lerpVectors(cameraMove.fromTarget,cameraMove.toTarget,e);camera.position.lerpVectors(cameraMove.fromPosition,cameraMove.toPosition,e);if(cameraMove.t>=1)cameraMove=null;}
  key.target.position.set(0,mode==='armoury'?0:floor.position.y+.9,0);key.target.updateMatrixWorld();
  controls.update();orientLights();
  for(const {socket,el} of rifle.socketLabels){const p=socket.getWorldPosition(new T.Vector3()).project(camera);el.hidden=!socketMarkers.visible||p.z>1;el.style.left=(p.x*.5+.5)*stage.clientWidth+'px';el.style.top=(-p.y*.5+.5)*stage.clientHeight-18+'px';}
  renderer.render(scene,camera);
 });
}catch(err){console.error(err);status.hidden=false;status.textContent='The viewer could not load. Reload in a browser with WebGL enabled.';}
